name: mosaic
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.3
  flutter_floating_bottom_bar: ^1.3.0
  google_fonts: ^6.3.2
  http: ^1.6.0
  isar_community: 3.3.0
  isar_community_flutter_libs: 3.3.0
  material_symbols_icons: ^4.2874.0
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  share_plus: ^12.0.1
  shared_preferences: ^2.5.3
  waterfall_flow: ^3.1.1
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_community_generator: 3.3.0
  flutter_launcher_icons: ^0.14.4
  package_rename: ^1.10.1

flutter:
  uses-material-design: true
  assets:
    - assets/placeholders/
    - assets/icons/
    - assets/app_icon/

package_rename_config:
  android:
    app_name: Mosaic
    package_name: com.vegetals.mosaic
    override_old_package: com.example.mosaic

  ios:
    app_name: Mosaic
    bundle_name: com.vegetals
    package_name: com.vegetals.mosaic
