// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:mosaic/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(GameTypeAdapter());
    registerAdapter(IgdbCoverAdapter());
    registerAdapter(IgdbGameAdapter());
    registerAdapter(IgdbGameInfoAdapter());
    registerAdapter(ItemAdapter());
    registerAdapter(ItemCategoryAdapter());
    registerAdapter(ItemStatusAdapter());
    registerAdapter(OpenLibraryAuthorAdapter());
    registerAdapter(OpenLibraryCreatedAdapter());
    registerAdapter(OpenLibraryEditionAdapter());
    registerAdapter(OpenLibraryEditionClassificationsAdapter());
    registerAdapter(OpenLibraryEditionContributorAdapter());
    registerAdapter(OpenLibraryEditionCreatedAdapter());
    registerAdapter(OpenLibraryEditionTypeAdapter());
    registerAdapter(OpenLibraryEditionsAdapter());
    registerAdapter(OpenLibraryEditionsDocAdapter());
    registerAdapter(OpenLibraryExcerptAdapter());
    registerAdapter(OpenLibraryIdentifiersAdapter());
    registerAdapter(OpenLibraryLinkAdapter());
    registerAdapter(OpenLibrarySearchDocAdapter());
    registerAdapter(OpenLibraryTypeAdapter());
    registerAdapter(OpenLibraryWorkAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(GameTypeAdapter());
    registerAdapter(IgdbCoverAdapter());
    registerAdapter(IgdbGameAdapter());
    registerAdapter(IgdbGameInfoAdapter());
    registerAdapter(ItemAdapter());
    registerAdapter(ItemCategoryAdapter());
    registerAdapter(ItemStatusAdapter());
    registerAdapter(OpenLibraryAuthorAdapter());
    registerAdapter(OpenLibraryCreatedAdapter());
    registerAdapter(OpenLibraryEditionAdapter());
    registerAdapter(OpenLibraryEditionClassificationsAdapter());
    registerAdapter(OpenLibraryEditionContributorAdapter());
    registerAdapter(OpenLibraryEditionCreatedAdapter());
    registerAdapter(OpenLibraryEditionTypeAdapter());
    registerAdapter(OpenLibraryEditionsAdapter());
    registerAdapter(OpenLibraryEditionsDocAdapter());
    registerAdapter(OpenLibraryExcerptAdapter());
    registerAdapter(OpenLibraryIdentifiersAdapter());
    registerAdapter(OpenLibraryLinkAdapter());
    registerAdapter(OpenLibrarySearchDocAdapter());
    registerAdapter(OpenLibraryTypeAdapter());
    registerAdapter(OpenLibraryWorkAdapter());
  }
}
